import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} flex flex-col h-screen`}>
        <Header />
        <main className='pl-3 pr-3 md:pr-0 md:pl-10 lg:pl-20'>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
